# Generated by Django 2.2.24 on 2022-09-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_auto_20220930_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='pokemon',
            new_name='name',
        ),
    ]
