# Generated by Django 2.2.24 on 2022-10-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_auto_20220930_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemons',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
