# Generated by Django 4.0.5 on 2022-10-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20221003_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='dtamina',
            new_name='stamina',
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
