# Generated by Django 4.0.5 on 2022-10-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_rename_dtamina_pokemonentity_stamina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
