# Generated by Django 4.0.5 on 2022-10-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_pokemonentity_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='description',
        ),
        migrations.AddField(
            model_name='pokemons',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
