# Generated by Django 4.0.5 on 2022-10-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_remove_pokemonentity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemons',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='title_jp',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
