# Generated by Django 4.0.5 on 2022-10-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0023_alter_pokemons_id_alter_pokemons_previous_evolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemons',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание покемона'),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Изображение покемона'),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название покемона на английском'),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='title_jp',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название покемона на японском'),
        ),
    ]
