# Generated by Django 4.0.5 on 2022-10-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0024_alter_pokemons_description_alter_pokemons_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='name',
            new_name='pokemon',
        ),
    ]
